# -*- compile-command: "pub get"; -*-

name: copy_v0
description: A GEP solution to the OpenAI Gym 'Copy-v0' environment.

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  gep:
    path: ../../../../gep
  gym:
    git:
      url: git://github.com/gmlewis/gym-http-api.git
      path: binding-dart/gym

dev_dependencies:
  test: ^1.0.0
