# -*- compile-command: "pub get"; -*-

name: gep
description: Gene Expression Programming (GEP) library in Dart.

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  meta: ^1.1.6
  gym:
    git:
      url: git://github.com/gmlewis/gym-http-api.git
      ref: bb94d4dcbd880a83db0ce415cd6cfecfb39e78a2
      path: binding-dart/gym

dev_dependencies:
  test: ^1.0.0
