# -*- compile-command: "pub get"; -*-

name: gep
description: Gene Expression Programming (GEP) library in Dart.

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  gym:
    git:
      url: git://github.com/gmlewis/gym-http-api.git
      path: binding-dart/gym

dev_dependencies:
  test: ^1.0.0
